<td>
	<select  name="{$users_extra_fields_field[fields].name}" id="{$users_extra_fields_field[fields].name}">
		<option value='' {if $users_extra_fields_field[fields].value eq ""} selected="selected"{/if}>Select a year</option>
		<option value='1900' {if $users_extra_fields_field[fields].value eq "1900"} selected="selected"{/if}>1900</option>
		<option value='1901' {if $users_extra_fields_field[fields].value eq "1901"} selected="selected"{/if}>1901</option>
		<option value='1902' {if $users_extra_fields_field[fields].value eq "1902"} selected="selected"{/if}>1902</option>
		<option value='1903' {if $users_extra_fields_field[fields].value eq "1903"} selected="selected"{/if}>1903</option>
		<option value='1904' {if $users_extra_fields_field[fields].value eq "1904"} selected="selected"{/if}>1904</option>
		<option value='1905' {if $users_extra_fields_field[fields].value eq "1905"} selected="selected"{/if}>1905</option>
		<option value='1906' {if $users_extra_fields_field[fields].value eq "1906"} selected="selected"{/if}>1906</option>
		<option value='1907' {if $users_extra_fields_field[fields].value eq "1907"} selected="selected"{/if}>1907</option>
		<option value='1908' {if $users_extra_fields_field[fields].value eq "1908"} selected="selected"{/if}>1908</option>
		<option value='1909' {if $users_extra_fields_field[fields].value eq "1909"} selected="selected"{/if}>1909</option>
		<option value='1910' {if $users_extra_fields_field[fields].value eq "1910"} selected="selected"{/if}>1910</option>
		<option value='1911' {if $users_extra_fields_field[fields].value eq "1911"} selected="selected"{/if}>1911</option>
		<option value='1912' {if $users_extra_fields_field[fields].value eq "1912"} selected="selected"{/if}>1912</option>
		<option value='1913' {if $users_extra_fields_field[fields].value eq "1913"} selected="selected"{/if}>1913</option>
		<option value='1914' {if $users_extra_fields_field[fields].value eq "1914"} selected="selected"{/if}>1914</option>
		<option value='1915' {if $users_extra_fields_field[fields].value eq "1915"} selected="selected"{/if}>1915</option>
		<option value='1916' {if $users_extra_fields_field[fields].value eq "1916"} selected="selected"{/if}>1916</option>
		<option value='1917' {if $users_extra_fields_field[fields].value eq "1917"} selected="selected"{/if}>1917</option>
		<option value='1918' {if $users_extra_fields_field[fields].value eq "1918"} selected="selected"{/if}>1918</option>
		<option value='1919' {if $users_extra_fields_field[fields].value eq "1919"} selected="selected"{/if}>1919</option>
		<option value='1920' {if $users_extra_fields_field[fields].value eq "1920"} selected="selected"{/if}>1920</option>
		<option value='1921' {if $users_extra_fields_field[fields].value eq "1921"} selected="selected"{/if}>1921</option>
		<option value='1922' {if $users_extra_fields_field[fields].value eq "1922"} selected="selected"{/if}>1922</option>
		<option value='1923' {if $users_extra_fields_field[fields].value eq "1923"} selected="selected"{/if}>1923</option>
		<option value='1924' {if $users_extra_fields_field[fields].value eq "1924"} selected="selected"{/if}>1924</option>
		<option value='1925' {if $users_extra_fields_field[fields].value eq "1925"} selected="selected"{/if}>1925</option>
		<option value='1926' {if $users_extra_fields_field[fields].value eq "1926"} selected="selected"{/if}>1926</option>
		<option value='1927' {if $users_extra_fields_field[fields].value eq "1927"} selected="selected"{/if}>1927</option>
		<option value='1928' {if $users_extra_fields_field[fields].value eq "1928"} selected="selected"{/if}>1928</option>
		<option value='1929' {if $users_extra_fields_field[fields].value eq "1929"} selected="selected"{/if}>1929</option>
		<option value='1930' {if $users_extra_fields_field[fields].value eq "1930"} selected="selected"{/if}>1930</option>
		<option value='1931' {if $users_extra_fields_field[fields].value eq "1931"} selected="selected"{/if}>1931</option>
		<option value='1932' {if $users_extra_fields_field[fields].value eq "1932"} selected="selected"{/if}>1932</option>
		<option value='1933' {if $users_extra_fields_field[fields].value eq "1933"} selected="selected"{/if}>1933</option>
		<option value='1934' {if $users_extra_fields_field[fields].value eq "1934"} selected="selected"{/if}>1934</option>
		<option value='1935' {if $users_extra_fields_field[fields].value eq "1935"} selected="selected"{/if}>1935</option>
		<option value='1936' {if $users_extra_fields_field[fields].value eq "1936"} selected="selected"{/if}>1936</option>
		<option value='1937' {if $users_extra_fields_field[fields].value eq "1937"} selected="selected"{/if}>1937</option>
		<option value='1938' {if $users_extra_fields_field[fields].value eq "1938"} selected="selected"{/if}>1938</option>
		<option value='1939' {if $users_extra_fields_field[fields].value eq "1939"} selected="selected"{/if}>1939</option>
		<option value='1940' {if $users_extra_fields_field[fields].value eq "1940"} selected="selected"{/if}>1940</option>
		<option value='1941' {if $users_extra_fields_field[fields].value eq "1941"} selected="selected"{/if}>1941</option>
		<option value='1942' {if $users_extra_fields_field[fields].value eq "1942"} selected="selected"{/if}>1942</option>
		<option value='1943' {if $users_extra_fields_field[fields].value eq "1943"} selected="selected"{/if}>1943</option>
		<option value='1944' {if $users_extra_fields_field[fields].value eq "1944"} selected="selected"{/if}>1944</option>
		<option value='1945' {if $users_extra_fields_field[fields].value eq "1945"} selected="selected"{/if}>1945</option>
		<option value='1946' {if $users_extra_fields_field[fields].value eq "1946"} selected="selected"{/if}>1946</option>
		<option value='1947' {if $users_extra_fields_field[fields].value eq "1947"} selected="selected"{/if}>1947</option>
		<option value='1948' {if $users_extra_fields_field[fields].value eq "1948"} selected="selected"{/if}>1948</option>
		<option value='1949' {if $users_extra_fields_field[fields].value eq "1949"} selected="selected"{/if}>1949</option>
		<option value='1950' {if $users_extra_fields_field[fields].value eq "1950"} selected="selected"{/if}>1950</option>
		<option value='1951' {if $users_extra_fields_field[fields].value eq "1951"} selected="selected"{/if}>1951</option>
		<option value='1952' {if $users_extra_fields_field[fields].value eq "1952"} selected="selected"{/if}>1952</option>
		<option value='1953' {if $users_extra_fields_field[fields].value eq "1953"} selected="selected"{/if}>1953</option>
		<option value='1954' {if $users_extra_fields_field[fields].value eq "1954"} selected="selected"{/if}>1954</option>
		<option value='1955' {if $users_extra_fields_field[fields].value eq "1955"} selected="selected"{/if}>1955</option>
		<option value='1956' {if $users_extra_fields_field[fields].value eq "1956"} selected="selected"{/if}>1956</option>
		<option value='1957' {if $users_extra_fields_field[fields].value eq "1957"} selected="selected"{/if}>1957</option>
		<option value='1958' {if $users_extra_fields_field[fields].value eq "1958"} selected="selected"{/if}>1958</option>
		<option value='1959' {if $users_extra_fields_field[fields].value eq "1959"} selected="selected"{/if}>1959</option>
		<option value='1960' {if $users_extra_fields_field[fields].value eq "1960"} selected="selected"{/if}>1960</option>
		<option value='1961' {if $users_extra_fields_field[fields].value eq "1961"} selected="selected"{/if}>1961</option>
		<option value='1962' {if $users_extra_fields_field[fields].value eq "1962"} selected="selected"{/if}>1962</option>
		<option value='1963' {if $users_extra_fields_field[fields].value eq "1963"} selected="selected"{/if}>1963</option>
		<option value='1964' {if $users_extra_fields_field[fields].value eq "1964"} selected="selected"{/if}>1964</option>
		<option value='1965' {if $users_extra_fields_field[fields].value eq "1965"} selected="selected"{/if}>1965</option>
		<option value='1966' {if $users_extra_fields_field[fields].value eq "1966"} selected="selected"{/if}>1966</option>
		<option value='1967' {if $users_extra_fields_field[fields].value eq "1967"} selected="selected"{/if}>1967</option>
		<option value='1968' {if $users_extra_fields_field[fields].value eq "1968"} selected="selected"{/if}>1968</option>
		<option value='1969' {if $users_extra_fields_field[fields].value eq "1969"} selected="selected"{/if}>1969</option>
		<option value='1970' {if $users_extra_fields_field[fields].value eq "1970"} selected="selected"{/if}>1970</option>
		<option value='1971' {if $users_extra_fields_field[fields].value eq "1971"} selected="selected"{/if}>1971</option>
		<option value='1972' {if $users_extra_fields_field[fields].value eq "1972"} selected="selected"{/if}>1972</option>
		<option value='1973' {if $users_extra_fields_field[fields].value eq "1973"} selected="selected"{/if}>1973</option>
		<option value='1974' {if $users_extra_fields_field[fields].value eq "1974"} selected="selected"{/if}>1974</option>
		<option value='1975' {if $users_extra_fields_field[fields].value eq "1975"} selected="selected"{/if}>1975</option>
		<option value='1976' {if $users_extra_fields_field[fields].value eq "1976"} selected="selected"{/if}>1976</option>
		<option value='1977' {if $users_extra_fields_field[fields].value eq "1977"} selected="selected"{/if}>1977</option>
		<option value='1978' {if $users_extra_fields_field[fields].value eq "1978"} selected="selected"{/if}>1978</option>
		<option value='1979' {if $users_extra_fields_field[fields].value eq "1979"} selected="selected"{/if}>1979</option>
		<option value='1980' {if $users_extra_fields_field[fields].value eq "1980"} selected="selected"{/if}>1980</option>
		<option value='1981' {if $users_extra_fields_field[fields].value eq "1981"} selected="selected"{/if}>1981</option>
		<option value='1982' {if $users_extra_fields_field[fields].value eq "1982"} selected="selected"{/if}>1982</option>
		<option value='1983' {if $users_extra_fields_field[fields].value eq "1983"} selected="selected"{/if}>1983</option>
		<option value='1984' {if $users_extra_fields_field[fields].value eq "1984"} selected="selected"{/if}>1984</option>
		<option value='1985' {if $users_extra_fields_field[fields].value eq "1985"} selected="selected"{/if}>1985</option>
		<option value='1986' {if $users_extra_fields_field[fields].value eq "1986"} selected="selected"{/if}>1986</option>
		<option value='1987' {if $users_extra_fields_field[fields].value eq "1987"} selected="selected"{/if}>1987</option>
		<option value='1988' {if $users_extra_fields_field[fields].value eq "1988"} selected="selected"{/if}>1988</option>
		<option value='1989' {if $users_extra_fields_field[fields].value eq "1989"} selected="selected"{/if}>1989</option>
		<option value='1990' {if $users_extra_fields_field[fields].value eq "1990"} selected="selected"{/if}>1990</option>
		<option value='1991' {if $users_extra_fields_field[fields].value eq "1991"} selected="selected"{/if}>1991</option>
		<option value='1992' {if $users_extra_fields_field[fields].value eq "1992"} selected="selected"{/if}>1992</option>
		<option value='1993' {if $users_extra_fields_field[fields].value eq "1993"} selected="selected"{/if}>1993</option>
		<option value='1994' {if $users_extra_fields_field[fields].value eq "1994"} selected="selected"{/if}>1994</option>
		<option value='1995' {if $users_extra_fields_field[fields].value eq "1995"} selected="selected"{/if}>1995</option>
		<option value='1996' {if $users_extra_fields_field[fields].value eq "1996"} selected="selected"{/if}>1996</option>
		<option value='1997' {if $users_extra_fields_field[fields].value eq "1997"} selected="selected"{/if}>1997</option>
		<option value='1998' {if $users_extra_fields_field[fields].value eq "1998"} selected="selected"{/if}>1998</option>
		<option value='1999' {if $users_extra_fields_field[fields].value eq "1999"} selected="selected"{/if}>1999</option>
		<option value='2000' {if $users_extra_fields_field[fields].value eq "2000"} selected="selected"{/if}>2000</option>
		<option value='2001' {if $users_extra_fields_field[fields].value eq "2001"} selected="selected"{/if}>2001</option>
		<option value='2002' {if $users_extra_fields_field[fields].value eq "2002"} selected="selected"{/if}>2002</option>
		<option value='2003' {if $users_extra_fields_field[fields].value eq "2003"} selected="selected"{/if}>2003</option>
		<option value='2004' {if $users_extra_fields_field[fields].value eq "2004"} selected="selected"{/if}>2004</option>
		<option value='2005' {if $users_extra_fields_field[fields].value eq "2005"} selected="selected"{/if}>2005</option>
		<option value='2006' {if $users_extra_fields_field[fields].value eq "2006"} selected="selected"{/if}>2006</option>
		<option value='2007' {if $users_extra_fields_field[fields].value eq "2007"} selected="selected"{/if}>2007</option>
		<option value='2008' {if $users_extra_fields_field[fields].value eq "2008"} selected="selected"{/if}>2008</option>
	</select>
</td>