<td>
	<select  name="{$users_extra_fields_field[fields].name}" id="{$users_extra_fields_field[fields].name}">
		<option value='' {if $users_extra_fields_field[fields].value eq ""} selected="selected"{/if}>Select an age</option>
		<option value='15' {if $users_extra_fields_field[fields].value eq "15"} selected="selected"{/if}>15</option>
		<option value='16' {if $users_extra_fields_field[fields].value eq "16"} selected="selected"{/if}>16</option>
		<option value='17' {if $users_extra_fields_field[fields].value eq "17"} selected="selected"{/if}>17</option>
		<option value='18' {if $users_extra_fields_field[fields].value eq "18"} selected="selected"{/if}>18</option>
		<option value='19' {if $users_extra_fields_field[fields].value eq "19"} selected="selected"{/if}>19</option>
		<option value='20' {if $users_extra_fields_field[fields].value eq "20"} selected="selected"{/if}>20</option>
		<option value='21' {if $users_extra_fields_field[fields].value eq "21"} selected="selected"{/if}>21</option>
		<option value='22' {if $users_extra_fields_field[fields].value eq "22"} selected="selected"{/if}>22</option>
		<option value='23' {if $users_extra_fields_field[fields].value eq "23"} selected="selected"{/if}>23</option>
		<option value='24' {if $users_extra_fields_field[fields].value eq "24"} selected="selected"{/if}>24</option>
		<option value='25' {if $users_extra_fields_field[fields].value eq "25"} selected="selected"{/if}>25</option>
		<option value='26' {if $users_extra_fields_field[fields].value eq "26"} selected="selected"{/if}>26</option>
		<option value='27' {if $users_extra_fields_field[fields].value eq "27"} selected="selected"{/if}>27</option>
		<option value='28' {if $users_extra_fields_field[fields].value eq "28"} selected="selected"{/if}>28</option>
		<option value='29' {if $users_extra_fields_field[fields].value eq "29"} selected="selected"{/if}>29</option>
		<option value='30' {if $users_extra_fields_field[fields].value eq "30"} selected="selected"{/if}>30</option>
		<option value='31' {if $users_extra_fields_field[fields].value eq "31"} selected="selected"{/if}>31</option>
		<option value='32' {if $users_extra_fields_field[fields].value eq "32"} selected="selected"{/if}>32</option>
		<option value='33' {if $users_extra_fields_field[fields].value eq "33"} selected="selected"{/if}>33</option>
		<option value='34' {if $users_extra_fields_field[fields].value eq "34"} selected="selected"{/if}>34</option>
		<option value='35' {if $users_extra_fields_field[fields].value eq "35"} selected="selected"{/if}>35</option>
		<option value='36' {if $users_extra_fields_field[fields].value eq "36"} selected="selected"{/if}>36</option>
		<option value='37' {if $users_extra_fields_field[fields].value eq "37"} selected="selected"{/if}>37</option>
		<option value='38' {if $users_extra_fields_field[fields].value eq "38"} selected="selected"{/if}>38</option>
		<option value='39' {if $users_extra_fields_field[fields].value eq "39"} selected="selected"{/if}>39</option>
		<option value='40' {if $users_extra_fields_field[fields].value eq "40"} selected="selected"{/if}>40</option>
		<option value='41' {if $users_extra_fields_field[fields].value eq "41"} selected="selected"{/if}>41</option>
		<option value='42' {if $users_extra_fields_field[fields].value eq "42"} selected="selected"{/if}>42</option>
		<option value='43' {if $users_extra_fields_field[fields].value eq "43"} selected="selected"{/if}>43</option>
		<option value='44' {if $users_extra_fields_field[fields].value eq "44"} selected="selected"{/if}>44</option>
		<option value='45' {if $users_extra_fields_field[fields].value eq "45"} selected="selected"{/if}>45</option>
		<option value='46' {if $users_extra_fields_field[fields].value eq "46"} selected="selected"{/if}>46</option>
		<option value='47' {if $users_extra_fields_field[fields].value eq "47"} selected="selected"{/if}>47</option>
		<option value='48' {if $users_extra_fields_field[fields].value eq "48"} selected="selected"{/if}>48</option>
		<option value='49' {if $users_extra_fields_field[fields].value eq "49"} selected="selected"{/if}>49</option>
		<option value='50' {if $users_extra_fields_field[fields].value eq "50"} selected="selected"{/if}>50</option>
		<option value='51' {if $users_extra_fields_field[fields].value eq "51"} selected="selected"{/if}>51</option>
		<option value='52' {if $users_extra_fields_field[fields].value eq "52"} selected="selected"{/if}>52</option>
		<option value='53' {if $users_extra_fields_field[fields].value eq "53"} selected="selected"{/if}>53</option>
		<option value='54' {if $users_extra_fields_field[fields].value eq "54"} selected="selected"{/if}>54</option>
		<option value='55' {if $users_extra_fields_field[fields].value eq "55"} selected="selected"{/if}>55</option>
		<option value='56' {if $users_extra_fields_field[fields].value eq "56"} selected="selected"{/if}>56</option>
		<option value='57' {if $users_extra_fields_field[fields].value eq "57"} selected="selected"{/if}>57</option>
		<option value='58' {if $users_extra_fields_field[fields].value eq "58"} selected="selected"{/if}>58</option>
		<option value='59' {if $users_extra_fields_field[fields].value eq "59"} selected="selected"{/if}>59</option>
		<option value='60' {if $users_extra_fields_field[fields].value eq "60"} selected="selected"{/if}>60</option>
		<option value='61' {if $users_extra_fields_field[fields].value eq "61"} selected="selected"{/if}>61</option>
		<option value='62' {if $users_extra_fields_field[fields].value eq "62"} selected="selected"{/if}>62</option>
		<option value='63' {if $users_extra_fields_field[fields].value eq "63"} selected="selected"{/if}>63</option>
		<option value='64' {if $users_extra_fields_field[fields].value eq "64"} selected="selected"{/if}>64</option>
		<option value='65' {if $users_extra_fields_field[fields].value eq "65"} selected="selected"{/if}>65</option>
		<option value='66' {if $users_extra_fields_field[fields].value eq "66"} selected="selected"{/if}>66</option>
		<option value='67' {if $users_extra_fields_field[fields].value eq "67"} selected="selected"{/if}>67</option>
		<option value='68' {if $users_extra_fields_field[fields].value eq "68"} selected="selected"{/if}>68</option>
		<option value='69' {if $users_extra_fields_field[fields].value eq "69"} selected="selected"{/if}>69</option>
		<option value='70' {if $users_extra_fields_field[fields].value eq "70"} selected="selected"{/if}>70</option>
		<option value='71' {if $users_extra_fields_field[fields].value eq "71"} selected="selected"{/if}>71</option>
		<option value='72' {if $users_extra_fields_field[fields].value eq "72"} selected="selected"{/if}>72</option>
		<option value='73' {if $users_extra_fields_field[fields].value eq "73"} selected="selected"{/if}>73</option>
		<option value='74' {if $users_extra_fields_field[fields].value eq "74"} selected="selected"{/if}>74</option>
		<option value='75' {if $users_extra_fields_field[fields].value eq "75"} selected="selected"{/if}>75</option>
		<option value='76' {if $users_extra_fields_field[fields].value eq "76"} selected="selected"{/if}>76</option>
		<option value='77' {if $users_extra_fields_field[fields].value eq "77"} selected="selected"{/if}>77</option>
		<option value='78' {if $users_extra_fields_field[fields].value eq "78"} selected="selected"{/if}>78</option>
		<option value='79' {if $users_extra_fields_field[fields].value eq "79"} selected="selected"{/if}>79</option>
		<option value='80' {if $users_extra_fields_field[fields].value eq "80"} selected="selected"{/if}>80</option>
		<option value='81' {if $users_extra_fields_field[fields].value eq "81"} selected="selected"{/if}>81</option>
		<option value='82' {if $users_extra_fields_field[fields].value eq "82"} selected="selected"{/if}>82</option>
		<option value='83' {if $users_extra_fields_field[fields].value eq "83"} selected="selected"{/if}>83</option>
		<option value='84' {if $users_extra_fields_field[fields].value eq "84"} selected="selected"{/if}>84</option>
		<option value='85' {if $users_extra_fields_field[fields].value eq "85"} selected="selected"{/if}>85</option>
		<option value='86' {if $users_extra_fields_field[fields].value eq "86"} selected="selected"{/if}>86</option>
		<option value='87' {if $users_extra_fields_field[fields].value eq "87"} selected="selected"{/if}>87</option>
		<option value='88' {if $users_extra_fields_field[fields].value eq "88"} selected="selected"{/if}>88</option>
		<option value='89' {if $users_extra_fields_field[fields].value eq "89"} selected="selected"{/if}>89</option>
		<option value='90' {if $users_extra_fields_field[fields].value eq "90"} selected="selected"{/if}>90</option>
		<option value='91' {if $users_extra_fields_field[fields].value eq "91"} selected="selected"{/if}>91</option>
		<option value='92' {if $users_extra_fields_field[fields].value eq "92"} selected="selected"{/if}>92</option>
		<option value='93' {if $users_extra_fields_field[fields].value eq "93"} selected="selected"{/if}>93</option>
		<option value='94' {if $users_extra_fields_field[fields].value eq "94"} selected="selected"{/if}>94</option>
		<option value='95' {if $users_extra_fields_field[fields].value eq "95"} selected="selected"{/if}>95</option>
		<option value='96' {if $users_extra_fields_field[fields].value eq "96"} selected="selected"{/if}>96</option>
		<option value='97' {if $users_extra_fields_field[fields].value eq "97"} selected="selected"{/if}>97</option>
		<option value='98' {if $users_extra_fields_field[fields].value eq "98"} selected="selected"{/if}>98</option>
		<option value='99' {if $users_extra_fields_field[fields].value eq "99"} selected="selected"{/if}>99</option>
	</select>
</td>