<!-- user_create.tpl -->

	<div id="createUserForm-modal"  title="{#PLIGG_Visual_AdminPanel_New_User#}">
	
       <div class="ui-widget ui-helper-hidden" id="errorblock-div1">
			<div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;" id="errorblock-div2" style="display:none;"> 
				<p>
				   <!-- JDR: fancy icon -->
				   <span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span> 
	               <strong>Alert:</strong> Errors detected!
				</p>
				<!-- JDR: validation plugin will target this UL for error messages -->
				<ul></ul>
			</div>
		</div>
		
		<!-- JDR: our form, no buttons (buttons generated by jQuery UI dialog() function) -->
	    <form action="admin_create_user.php" method="post" id="createUserForm" class="form">	
			{$hidden_token_admin_users_create}
			<label for="username">{#PLIGG_Visual_Register_Username#}:</label>
			<div class="div_texbox">
				<input name="username" type="text" class="textbox" id="username" value="" />
			</div>
			{if isset($username_error)}
				<div class="alert">
					<button class="close" data-dismiss="alert">×</button>
					{ foreach value=error from=$username_error }
						<p class="error">{$error}</p>
					{ /foreach }
				</div>
			{/if}	
			<div style="clear:both;"></div>
			<label for="email">{#PLIGG_Visual_Register_Email#}:</label>
			<div class="div_texbox">
				<input name="email" type="text" class="textbox" id="city" value="" />
			</div>
			{if isset($email_error)}
				<div class="alert">
					<button class="close" data-dismiss="alert">×</button>
					{ foreach value=error from=$email_error }
						<p class="error">{$error}</p>
					{ /foreach }
				</div>
			{/if}	
			<div style="clear:both;"></div>
			<label>{#PLIGG_Visual_View_User_Level#}:</label>
			<div class="div_texbox">
				<select name="level">
					<option value="normal">Normal</option>
					<option value="moderator">Moderator</option>
					<option value="admin">Admin</option>
				</select>
			</div>
			<div style="clear:both;"></div>
			<label for="password">{#PLIGG_Visual_Register_Password#}:</label>
			<div class="div_texbox">
				<input name="password" type="text" class="textbox" id="password" value="" />
			</div>
			{if isset($password_error)}
				<div class="alert">
					<button class="close" data-dismiss="alert">×</button>
					{ foreach value=error from=$password_error }
						<p class="error">{$error}</p>
					{ /foreach }
				</div>
			{/if}	
			<div style="clear:both;"></div>
			<div class="buton_div">
				<input type="hidden" name="mode" value="newuser">
				
			</div>
		 </form>
	
    
   
    </div>

	<!--/user_create.tpl -->